-- Unit tests for Unicode backend
local unicode = require('unicode-math.backends.unicode')

describe("Unicode Backend", function()
    describe("Basic Setup", function()
        it("should initialize without errors", function()
            local config = { renderer = "unicode" }
            unicode.setup(config)
            assert_not_nil(unicode)
        end)
        
        it("should have render function", function()
            assert_not_nil(unicode.render)
            assert_equal(type(unicode.render), "function")
        end)
        
        it("should have convert_to_unicode function", function()
            assert_not_nil(unicode.convert_to_unicode)
            assert_equal(type(unicode.convert_to_unicode), "function")
        end)
    end)
    
    describe("Basic LaTeX to Unicode Conversion", function()
        it("should handle empty input", function()
            assert_equal(unicode.convert_to_unicode(""), "")
            assert_equal(unicode.convert_to_unicode(nil), "")
        end)
        
        it("should pass through non-LaTeX text", function()
            assert_equal(unicode.convert_to_unicode("hello world"), "hello world")
            assert_equal(unicode.convert_to_unicode("123 + 456"), "123 + 456")
        end)
        
        it("should convert basic Greek letters", function()
            assert_equal(unicode.convert_to_unicode("\\alpha"), "α")
            assert_equal(unicode.convert_to_unicode("\\beta"), "β")
            assert_equal(unicode.convert_to_unicode("\\gamma"), "γ")
            assert_equal(unicode.convert_to_unicode("\\delta"), "δ")
            assert_equal(unicode.convert_to_unicode("\\epsilon"), "ε")
            assert_equal(unicode.convert_to_unicode("\\pi"), "π")
            assert_equal(unicode.convert_to_unicode("\\sigma"), "σ")
            assert_equal(unicode.convert_to_unicode("\\omega"), "ω")
        end)
        
        it("should convert uppercase Greek letters", function()
            assert_equal(unicode.convert_to_unicode("\\Alpha"), "Α")
            assert_equal(unicode.convert_to_unicode("\\Beta"), "Β")
            assert_equal(unicode.convert_to_unicode("\\Gamma"), "Γ")
            assert_equal(unicode.convert_to_unicode("\\Delta"), "Δ")
            assert_equal(unicode.convert_to_unicode("\\Pi"), "Π")
            assert_equal(unicode.convert_to_unicode("\\Sigma"), "Σ")
            assert_equal(unicode.convert_to_unicode("\\Omega"), "Ω")
        end)
        
        it("should convert mathematical operators", function()
            assert_equal(unicode.convert_to_unicode("\\infty"), "∞")
            assert_equal(unicode.convert_to_unicode("\\sum"), "∑")
            assert_equal(unicode.convert_to_unicode("\\prod"), "∏")
            assert_equal(unicode.convert_to_unicode("\\int"), "∫")
            assert_equal(unicode.convert_to_unicode("\\partial"), "∂")
            assert_equal(unicode.convert_to_unicode("\\nabla"), "∇")
            assert_equal(unicode.convert_to_unicode("\\sqrt"), "√")
        end)
        
        it("should convert relations", function()
            assert_equal(unicode.convert_to_unicode("\\leq"), "≤")
            assert_equal(unicode.convert_to_unicode("\\geq"), "≥")
            assert_equal(unicode.convert_to_unicode("\\neq"), "≠")
            assert_equal(unicode.convert_to_unicode("\\approx"), "≈")
            assert_equal(unicode.convert_to_unicode("\\equiv"), "≡")
            assert_equal(unicode.convert_to_unicode("\\sim"), "∼")
        end)
        
        it("should convert set theory symbols", function()
            assert_equal(unicode.convert_to_unicode("\\in"), "∈")
            assert_equal(unicode.convert_to_unicode("\\notin"), "∉")
            assert_equal(unicode.convert_to_unicode("\\subset"), "⊂")
            assert_equal(unicode.convert_to_unicode("\\supset"), "⊃")
            assert_equal(unicode.convert_to_unicode("\\cap"), "∩")
            assert_equal(unicode.convert_to_unicode("\\cup"), "∪")
            assert_equal(unicode.convert_to_unicode("\\emptyset"), "∅")
        end)
        
        it("should convert logic symbols", function()
            assert_equal(unicode.convert_to_unicode("\\forall"), "∀")
            assert_equal(unicode.convert_to_unicode("\\exists"), "∃")
            assert_equal(unicode.convert_to_unicode("\\neg"), "¬")
            assert_equal(unicode.convert_to_unicode("\\land"), "∧")
            assert_equal(unicode.convert_to_unicode("\\lor"), "∨")
        end)
        
        it("should convert arrows", function()
            assert_equal(unicode.convert_to_unicode("\\leftarrow"), "←")
            assert_equal(unicode.convert_to_unicode("\\rightarrow"), "→")
            assert_equal(unicode.convert_to_unicode("\\leftrightarrow"), "↔")
            assert_equal(unicode.convert_to_unicode("\\Leftarrow"), "⇐")
            assert_equal(unicode.convert_to_unicode("\\Rightarrow"), "⇒")
            assert_equal(unicode.convert_to_unicode("\\Leftrightarrow"), "⇔")
        end)
    end)
    
    describe("Complex Expressions", function()
        it("should handle multiple symbols in one expression", function()
            assert_equal(unicode.convert_to_unicode("\\alpha + \\beta"), "α + β")
            assert_equal(unicode.convert_to_unicode("\\sum \\alpha \\leq \\infty"), "∑ α ≤ ∞")
        end)
        
        it("should handle symbols with word boundaries", function()
            assert_equal(unicode.convert_to_unicode("\\alpha x"), "α x")
            assert_equal(unicode.convert_to_unicode("\\pi r"), "π r")
            assert_equal(unicode.convert_to_unicode("\\theta = 0"), "θ = 0")
        end)
        
        it("should handle symbols at end of string", function()
            assert_equal(unicode.convert_to_unicode("f(\\alpha)"), "f(α)")
            assert_equal(unicode.convert_to_unicode("\\lim_{x \\to \\infty}"), "lim[x → ∞]")
        end)
    end)
    
    describe("MathBB Symbols", function()
        it("should convert mathbb symbols", function()
            assert_equal(unicode.convert_to_unicode("\\mathbb{N}"), "ℕ")
            assert_equal(unicode.convert_to_unicode("\\mathbb{Z}"), "ℤ")
            assert_equal(unicode.convert_to_unicode("\\mathbb{Q}"), "ℚ")
            assert_equal(unicode.convert_to_unicode("\\mathbb{R}"), "ℝ")
            assert_equal(unicode.convert_to_unicode("\\mathbb{C}"), "ℂ")
        end)
        
        it("should handle unknown mathbb symbols", function()
            assert_equal(unicode.convert_to_unicode("\\mathbb{X}"), "𝕏")
            assert_equal(unicode.convert_to_unicode("\\mathbb{Y}"), "𝕐")
        end)
        
        it("should preserve unknown mathbb symbols", function()
            assert_equal(unicode.convert_to_unicode("\\mathbb{unknown}"), "\\mathbb{unknown}")
        end)
    end)
    
    describe("Edge Cases", function()
        it("should handle backslash without command", function()
            assert_equal(unicode.convert_to_unicode("\\"), "\\")
            assert_equal(unicode.convert_to_unicode("\\unknown"), "\\unknown")
        end)
        
        it("should handle mixed LaTeX and regular text", function()
            assert_equal(unicode.convert_to_unicode("The value of \\pi is approximately 3.14"), "The value of π is approximately 3.14")
            assert_equal(unicode.convert_to_unicode("Let \\alpha = 5 and \\beta = 10"), "Let α = 5 and β = 10")
        end)
        
        it("should handle consecutive symbols", function()
            assert_equal(unicode.convert_to_unicode("\\alpha\\beta"), "αβ")
            assert_equal(unicode.convert_to_unicode("\\sum\\int"), "∑∫")
        end)
    end)
end)